Repository DEFRA/flood-risk-front-office, pull requests merged in 2019-06, with the labels that each got.

#206 Update Travis config
  .travis.yml
  Gemfile.lock
Labels: housekeeping

#208 Update dependencies
  Gemfile
  Gemfile.lock
Labels: housekeeping

#207 Inherit engine styles
  app/assets/stylesheets/application.css.scss
Labels: feature

#215 Update README badges
  README.md
Labels: housekeeping

#221 Delete unused schedule.rb file
  config/schedule.rb
Labels: fix

#227 Add github changelog generator to the project
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/tasks/changelog.rake
Labels: housekeeping

#228 Move github changelog generator to main group
  Gemfile
Labels: bug
