Repository DEFRA/flood-risk-front-office, pull requests merged in 2021-11, with the labels that each got.

#385 Rebuild DB to include timestamps for transient records
  Gemfile.lock
  db/schema.rb
Labels: bug

#386 Open footer links in same window
  app/views/layouts/application.html.erb
Labels: enhancement

#401 Update gems
  Gemfile.lock
Labels: dependencies
