Repository DEFRA/flood-risk-front-office, pull requests merged in 2021-09, with the labels that each got.

#364 Styling: Cookies page - Enhancements
  app/views/pages/cookies.html.erb
Labels: enhancement

#365 Update engine to use new reg workflow
  Gemfile.lock
  db/schema.rb
Labels: enhancement

#366 Update flood_risk_engine
  Gemfile.lock
Labels: dependencies

#368 Update engine
  Gemfile.lock
Labels: dependencies

#369 Update engine and fix titles
  Gemfile.lock
  app/controllers/application_controller.rb
  app/views/cookies/_action_confirmed.html.erb
  app/views/cookies/_action_required.html.erb
  app/views/layouts/application.html.erb
  app/views/pages/cookies.html.erb
  spec/features/new_registration_spec.rb
Labels: dependencies

#370 Update engine
  Gemfile.lock
Labels: dependencies

#371 Remove 'go back' link after cookies update
  app/views/pages/cookies.html.erb
  config/locales/cookies.en.yml
  spec/features/cookies_spec.rb
Labels: enhancement

#372 Update engine
  Gemfile.lock
Labels: dependencies

#374 Remove gem: jquery-rails
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
Labels: dependencies

#376 Bump the defra_ruby_template
  Gemfile.lock
Labels: dependencies

#377 Add _ga cookie details to the cookies policy page
  app/views/pages/cookies.html.erb
  config/locales/cookies.en.yml
Labels: enhancement

#375 Upgrade to Rails 6.1
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/test.rb
Labels: dependencies

#379 Update engine and configure default assistance mode
  Gemfile.lock
  config/initializers/flood_risk_engine.rb
Labels: enhancement

#380 Restore jQuery
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
Labels: dependencies

#381 Update the content security policy
  config/initializers/secure_headers.rb
Labels: enhancement

#383 Update the CSP
  config/initializers/secure_headers.rb
Labels: bug

#384 Revert the CSP to be the same as WCR
  config/initializers/secure_headers.rb
Labels: bug
